{
 "title": "IMON WebGUI Selfmon",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "WebGUIhost", "label": "WebGUIhost", "query": "label_values(webguihost)" }
  ]
 },
 "panels": [
  {
   "title": "JVM heap usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(1,os_webgui_jvm_usage_num{webguihost=\"$WebGUIhost\"}/os_webgui_jvm_max_num{webguihost=\"$WebGUIhost\"}*100)"
    }
   ]
  },
  {
   "title": "JVM heap usage",
   "type": "graph",
   "description": "Utilization of the Java Virtual Memory (JVM).",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_jvm_usage_num{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "jvm heap usage on {{webguihost}}"
    },
    {
     "expr": "topk(1,os_webgui_jvm_max_num{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "available jvm heap on {{webguihost}}"
    }
   ]
  },
  {
   "title": "SQL respone times ",
   "type": "graph",
   "description": "Response time, in second, of the datasource to all  SQL queries ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_sql_avg_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "SQL avg response time"
    },
    {
     "expr": "topk(1,os_webgui_sql_max_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "SQL max response time"
    }
   ]
  },
  {
   "title": "Cache sizes and hitrates",
   "type": "graph",
   "description": "Shows the efficiency of the cache by measuring the queries that are answered by cached data.  ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_datasource_cache_size_num{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "{{datasource}}  size"
    },
    {
     "expr": "topk(1,os_webgui_datasource_cache_hitrate_pc{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "{{datasource}} hitrate"
    }
   ]
  },
  {
   "title": "Event data services response times",
   "type": "graph",
   "description": "Response time, in second, of the datasource to query event data, for example for the Event Viewers and Active Events Lists. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_event_data_service_avg_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Average response"
    },
    {
     "expr": "topk(1,os_webgui_event_data_service_max_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Maximum response"
    }
   ]
  },
  {
   "title": "VMM Inserts",
   "type": "graph",
   "description": "Events inserted into the configured data sources acting primary ObjectServer, based on the configured thresholds for the VMM service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_vmm_avg_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "topk(1,os_webgui_vmm_max_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Event summary data services response times",
   "type": "graph",
   "description": "Response time, in seconds, of the datasource to query event summary data, such as Maps and Event Dashboards. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_event_summary_data_service_avg_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Average response"
    },
    {
     "expr": "topk(1,os_webgui_event_summary_data_service_max_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Maximum response"
    }
   ]
  },
  {
   "title": "Security repository response times",
   "type": "graph",
   "description": "Response time, in second, of the security repository. The security repositiory is definied as the ObjectServer that is used as the user registry, or file-based repository or LDAP directory.  ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_security_repository_avg_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Average response"
    },
    {
     "expr": "topk(1,os_webgui_security_repository_max_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Maximum response"
    }
   ]
  },
  {
   "title": "Metric data services response times",
   "type": "graph",
   "description": "Response time, in second, of the datasource to query metrics data, which is used to populate gauges.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_webgui_metric_data_service_avg_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Average response"
    },
    {
     "expr": "topk(1,os_webgui_metric_data_service_max_response_sec{webguihost=\"$WebGUIhost\"})",
     "legendFormat": "Maximum response"
    }
   ]
  }
 ]
}