{
 "title": "prometheus objectserver",
 "tags": [
  "tivoli",
  "ibm",
  "omnibus",
  "netcool",
  "objectserver"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "OSname", "label": "Objectserver", "query": "label_values(objectserver)" },
   { "name": "HostServer", "label": "HostServer", "query": "label_values(hostserver)" }
  ]
 },
 "panels": [
  {
   "title": "OS Felder",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_columns_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Events Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_events_total{objectserver=\"$OSname\"}",
     "legendFormat": "{{osname}}"
    }
   ]
  },
  {
   "title": "Alerts details Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_alerts_details_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Alerts journal Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_alerts_journal_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Drilldown Dashboards",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "content": "\nObjectserver Host Performance: [Host](http://localhost:3000/d/X9Ojx9OZk/prometheus-system?orgId=1)\n\n\nObjectserver Memstore Dashboard: [Memstore](http://localhost:3000/d/Ko3yTMRWz/prometheus-objectserver-memstore?orgId=1&refresh=15s)\n\nObjectserver Trigger Dashboard: [Trigger](http://localhost:3000/d/QsvGieeik/prometheus-objectserver-trigger?orgId=1&from=now-3h&to=now&var-OSname=AGG_P_A)\n\nObjectserver Profiles Dashboard: [Profiles](http://localhost:3000/d/_ybAzKgWz/prometheus-objectserver-profiles?orgId=1)\n\n\n"
  },
  {
   "title": "Master_Store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{objectserver=\"$OSname\",storename=\"master_store\"}"
    }
   ]
  },
  {
   "title": "Table_Store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{objectserver=\"$OSname\",storename=\"table_store\"}"
    }
   ]
  },
  {
   "title": "Temp_store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{objectserver=\"$OSname\",storename=\"temp_store\"}"
    }
   ]
  },
  {
   "title": "Virtual_store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{objectserver=\"$OSname\",storename=\"virtual_store\"}"
    }
   ]
  },
  {
   "title": "Connections Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_connections_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Current profiles",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_profiles_total_num{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "max SQL Time",
   "type": "singlestat",
   "description": "Longest running time, in seconds, for any client.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(os_profiles_maxsqltime_sec{objectserver=\"$OSname\"})"
    }
   ]
  },
  {
   "title": "max Period SQL Time",
   "type": "singlestat",
   "description": "Amount of time, in seconds, that the application has spent running SQL since the last profile report.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(os_profiles_periodsqltime_sec{objectserver=\"$OSname\"})"
    }
   ]
  },
  {
   "title": "Alerts Table Sizes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "os_events_total{objectserver=\"$OSname\"}",
     "legendFormat": "Events"
    },
    {
     "expr": "os_alerts_details_total{objectserver=\"$OSname\"}",
     "legendFormat": "Details"
    },
    {
     "expr": "os_alerts_journal_total{objectserver=\"$OSname\"}",
     "legendFormat": "Journal"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "os_events_critical_total{objectserver=\"$OSname\"}",
     "legendFormat": "Critical"
    },
    {
     "expr": "os_events_major_total{objectserver=\"$OSname\"}",
     "legendFormat": "Major"
    },
    {
     "expr": "os_events_minor_total{objectserver=\"$OSname\"}",
     "legendFormat": "Minor"
    },
    {
     "expr": "os_events_warning_total{objectserver=\"$OSname\"}",
     "legendFormat": "Warning"
    },
    {
     "expr": "os_events_indeterminate_total{objectserver=\"$OSname\"}",
     "legendFormat": "Indeterminate"
    },
    {
     "expr": "os_events_clear_total{objectserver=\"$OSname\"}",
     "legendFormat": "Clear"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "os_connections_total{objectserver=\"$OSname\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "sum(os_connections_connecttime) by (hostserver, objectserver, appname, logname)"
    }
   ]
  },
  {
   "title": "Triggers Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Triggers active",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_active_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Triggers inactive",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_inactive_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Current 10 slowest Trigger",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "topk(10,sum (os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=~\".+\"}) by (objectserver, trigger))",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "Total Time last Period",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=~\".+\"})"
    }
   ]
  },
  {
   "title": "Total Raise last Period",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_trigger_stats_periodnumraises{objectserver=\"$OSname\",trigger=~\".+\"})"
    }
   ]
  },
  {
   "title": "Total Fired last Period",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_trigger_stats_periodnumfires{objectserver=\"$OSname\",trigger=~\".+\"})"
    }
   ]
  },
  {
   "title": "Top 10  Trigger time last period",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,max without(active)(os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=~\".+\"}))",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "Top 10  Trigger raised last period",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,max without (active)(os_trigger_stats_periodnumraises{objectserver=\"$OSname\",trigger=~\".+\"}))",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "Top 10 Trigger fired last Period (without status_updates and state_change)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,max without(active)(os_trigger_stats_periodnumfires{objectserver=\"$OSname\",trigger=~\".+\",trigger!=\"status_updates\",trigger!=\"state_change\"}))",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "Trigger fired last Period (only status_updates and state_change)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "os_trigger_stats_periodnumfires{objectserver=\"$OSname\",trigger=~\"status_updates|state_change\"}",
     "legendFormat": "{{trigger}}"
    }
   ]
  }
 ]
}