{
 "title": "prometheus objectserver trigger",
 "tags": [
  "ibm",
  "netcool",
  "omnibus",
  "tivoli",
  "trigger",
  "objectserver"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "OSname", "label": "Objectserver", "query": "label_values(objectserver)" },
   { "name": "HostServer", "label": "hostserver", "query": "label_values(hostserver)" },
   { "name": "trigger", "label": "Trigger", "query": "label_values(trigger)" }
  ]
 },
 "panels": [
  {
   "title": "Trigger Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_trigger_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Trigger activ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_trigger_active_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Trigger inactive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_trigger_inactive_total{objectserver=\"$OSname\"}"
    }
   ]
  },
  {
   "title": "Slowest Trigger",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(topk(1,os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=~\".+\"}))"
    }
   ]
  },
  {
   "title": "Top 5 slowest Trigger",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,sum(os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=~\".+\"}) by (objectserver, trigger))"
    }
   ]
  },
  {
   "title": "$trigger raises",
   "type": "singlestat",
   "description": "Number of raises during the last period for the $trigger trigger on objectserver $OSname",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_stats_periodnumraises{objectserver=\"$OSname\",trigger=\"$trigger\"}"
    }
   ]
  },
  {
   "title": "$trigger fired",
   "type": "singlestat",
   "description": "How often $trigger trigger was fired during the last period for the  on objectserver $OSname",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_stats_periodnumfires{objectserver=\"$OSname\",trigger=\"$trigger\"}"
    }
   ]
  },
  {
   "title": "$trigger  current time",
   "type": "singlestat",
   "description": "Current execution time for the $trigger trigger on objectserver $OSname",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=\"$trigger\"}"
    }
   ]
  },
  {
   "title": "Slowest Trigger",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1,os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=~\".+\"})",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "$trigger raises average",
   "type": "singlestat",
   "description": "Average number of raises during the last period for the $trigger trigger on objectserver $OSname",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_trigger_stats_periodnumraises{objectserver=\"$OSname\",trigger=\"$trigger\"}"
    }
   ]
  },
  {
   "title": "$trigger fired average",
   "type": "singlestat",
   "description": "How often $trigger trigger was fired during the last period for the  on objectserver $OSname",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_trigger_stats_periodnumfires{objectserver=\"$OSname\",trigger=\"$trigger\"}"
    }
   ]
  },
  {
   "title": "$trigger average time",
   "type": "singlestat",
   "description": "Average execution time for the $trigger trigger on objectserver $OSname",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=\"$trigger\"}[360m]"
    }
   ]
  },
  {
   "title": "time / raise / fires during last period for $trigger trigger",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "counts" }
   ],
   "targets": [
    {
     "expr": "os_trigger_stats_periodnumraises{objectserver=\"$OSname\",trigger=\"$trigger\"}",
     "legendFormat": "raises"
    },
    {
     "expr": "os_trigger_stats_periodnumfires{objectserver=\"$OSname\",trigger=\"$trigger\"}",
     "legendFormat": "fires"
    },
    {
     "expr": "os_trigger_stats_periodtime_sec{objectserver=\"$OSname\",trigger=\"$trigger\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 } }
 ]
}