{
 "title": "prometheus objectserver memstore",
 "tags": [
  "ibm",
  "netcool",
  "tivoli",
  "omnibus",
  "objectserver",
  "memstore"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "OSname", "label": "Objectserver", "query": "label_values(objectserver)" },
   { "name": "HostServer", "label": "hostserver", "query": "label_values(hostserver)" }
  ]
 },
 "panels": [
  {
   "title": "Memstore Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=~\".+\"}",
     "legendFormat": "{{storename}}"
    }
   ]
  },
  {
   "title": "Master_store usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"master_store\"}/(os_memstore_hardlimit_bytes{objectserver=\"$OSname\",storename=\"master_store\"}/100)"
    }
   ]
  },
  {
   "title": "Master_store",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"master_store\"}",
     "legendFormat": "Used bytes"
    },
    {
     "expr": "os_memstore_hardlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"master_store\"}",
     "legendFormat": "Hardlimit"
    },
    {
     "expr": "os_memstore_softlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"master_store\"}",
     "legendFormat": "Softlimit"
    }
   ]
  },
  {
   "title": "Table_store usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"table_store\"}/(os_memstore_hardlimit_bytes{objectserver=\"$OSname\",storename=\"table_store\"}/100)"
    }
   ]
  },
  {
   "title": "Table_store",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"table_store\"}",
     "legendFormat": "Used bytes"
    },
    {
     "expr": "os_memstore_hardlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"table_store\"}",
     "legendFormat": "Hardlimit"
    },
    {
     "expr": "os_memstore_softlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"table_store\"}",
     "legendFormat": "Softlimit"
    }
   ]
  },
  {
   "title": "Temp_store usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"temp_store\"}/(os_memstore_hardlimit_bytes{objectserver=\"$OSname\",storename=\"temp_store\"}/100)"
    }
   ]
  },
  {
   "title": "Temp_store",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"temp_store\"}",
     "legendFormat": "Used bytes"
    },
    {
     "expr": "os_memstore_hardlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"temp_store\"}",
     "legendFormat": "Hardlimit"
    },
    {
     "expr": "os_memstore_softlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"temp_store\"}",
     "legendFormat": "Softlimit"
    }
   ]
  },
  {
   "title": "Virtual_store usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"virtual_store\"}/(os_memstore_hardlimit_bytes{objectserver=\"$OSname\",storename=\"virtual_store\"}/100)"
    }
   ]
  },
  {
   "title": "Virtual_store",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_memstore_usedbytes_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"virtual_store\"}",
     "legendFormat": "Used bytes"
    },
    {
     "expr": "os_memstore_hardlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"virtual_store\"}",
     "legendFormat": "Hardlimit"
    },
    {
     "expr": "os_memstore_softlimit_bytes{hostserver=\"$HostServer\",objectserver=\"$OSname\",storename=\"virtual_store\"}",
     "legendFormat": "Softlimit"
    }
   ]
  }
 ]
}