{
 "title": "prometheus objectserver profiles",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "OSname", "query": "label_values(objectserver)" }
  ]
 },
 "panels": [
  {
   "title": "Max SQLTime by Application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(os_profiles_lastsqltime_sec{objectserver=\"$OSname\"}) by (objectserver, appname)",
     "legendFormat": "{{appname}}"
    }
   ]
  },
  {
   "title": "Max SQLTime by User Id",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(os_profiles_lastsqltime_sec{objectserver=\"$OSname\"}) by (objectserver, uid)",
     "legendFormat": "{{uid}}"
    }
   ]
  },
  {
   "title": "Max SQLTime by Hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(os_profiles_lastsqltime_sec{objectserver=\"$OSname\"}) by (objectserver, hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 } }
 ]
}