{
 "title": "prometheus objecterserver_exporter performance",
 "tags": [
  "IMON",
  "Selfmonitoring",
  "perfomance",
  "scraping"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PyVersion",
    "label": "PyVersion",
    "query": "label_values(python_info,version)"
   }
  ]
 },
 "panels": [
  {
   "title": "Python Version",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "python_info" }
   ]
  },
  {
   "title": "Number of threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "osexporter_self_totalthreads_num",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Total scraping time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(osexporter_self_osscrapetimetotal_sec) by (hostserver)",
     "legendFormat": "{{hostserver}}"
    }
   ]
  },
  {
   "title": "Python GC uncollectable objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(python_gc_objects_uncollectable_total)",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Python Garbage Collection Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(python_gc_collections_total[5m])",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "process resident memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Python GC Objects collected total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Virtual memory per process",
   "type": "graph",
   "description": "Process_virtual_memory_bytes Virtual memory size in bytes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 } }
 ]
}