{
 "title": "Objectserver Diff",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "objectserver1", "label": "Objectserver 1", "query": "label_values(objectserver)" },
   { "name": "objectserver2", "label": "Objectserver 2", "query": "label_values(objectserver)" }
  ]
 },
 "panels": [
  {
   "title": "Objectserver 1",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "content": "$objectserver1\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Diff",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "content": "Difference Absolut\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Objectserver 2",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "content": "$objectserver2\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_events_total{objectserver='$objectserver1'}"
    }
   ]
  },
  {
   "title": "alerts status columns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_columns_total{objectserver='$objectserver1'}"
    }
   ]
  },
  {
   "title": "Trigger total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_total{objectserver='$objectserver1'}"
    }
   ]
  },
  {
   "title": "Absolut Events Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "abs(os_events_total{objectserver='$objectserver1'} - ignoring(objectserver,env,hostserver,instance,job) os_events_total{objectserver='$objectserver2'})"
    }
   ]
  },
  {
   "title": "alerts.status columns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "abs(os_columns_total{objectserver='$objectserver1'} - ignoring(objectserver,env,hostserver,instance,job) os_columns_total{objectserver='$objectserver2'})"
    }
   ]
  },
  {
   "title": "Trigger Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(os_trigger_stats_totaltime_sec{objectserver=~'$objectserver1|$objectserver2'}) by (trigger) < 2)"
    }
   ]
  },
  {
   "title": "Current Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_events_total{objectserver='$objectserver2'}"
    }
   ]
  },
  {
   "title": "alerts status columns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_columns_total{objectserver='$objectserver2'}"
    }
   ]
  },
  {
   "title": "Trigger total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_trigger_total{objectserver='$objectserver2'}"
    }
   ]
  },
  {
   "title": "Columns only on 1 OS",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(os_columns_details{objectserver=~'$objectserver1|$objectserver2'}) by (columnname) < 2"
    }
   ]
  },
  {
   "title": "Triggers only on 1 OS",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "count(os_trigger_stats_totaltime_sec{objectserver=~'$objectserver1|$objectserver2'}) by (trigger) < 2"
    }
   ]
  }
 ]
}