{
 "title": "Impact Selfmon",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ImpactHost", "label": "Impact Host", "query": "label_values(impacthost)" }
  ]
 },
 "panels": [
  {
   "title": "Heap usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(os_impact_heap_used_num{impacthost=\"$ImpactHost\"}/os_impact_heap_max_num{impacthost=\"$ImpactHost\"})*100",
     "legendFormat": "{{impacthost}}"
    }
   ]
  },
  {
   "title": "Impact heap used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "os_impact_heap_used_num{impacthost=\"$ImpactHost\"}",
     "legendFormat": "Impact heapused on {{impacthost}}"
    },
    {
     "expr": "os_impact_heap_max_num{impacthost=\"$ImpactHost\"}",
     "legendFormat": "impact max heap on {{impacthost}}"
    }
   ]
  },
  {
   "title": "Queue sizes table",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "os_impact_queue_size_num{impacthost=\"$ImpactHost\"}"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "os_impact_queue_size_num{impacthost=\"$ImpactHost\"}",
     "legendFormat": "{{queuename}} on {{impacthost}}"
    }
   ]
  }
 ]
}